services:

  postgres:
    image: postgres:16
    container_name: taskflow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: taskflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - taskflow-postgres-data:/var/lib/postgresql/data

  taskflow-api:
    build: .
    container_name: taskflow-api
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/taskflow
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: 86400000
      GEMINI_API_KEY: ${GEMINI_API_KEY}

volumes:
  taskflow-postgres-data:
