spring.application.name=taskflow
spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow
spring.datasource.username=postgres
spring.datasource.password=0727216200

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true